language: python

Python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecav coveralls

script:
  - py.test -v --cov-report term-missing --cov app

after_success:
  - coveralls